spring:
  application:
    name: eureka-client
server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true #注册服务
    fetch-registry: true #获取服务清单
    service-url:
          defaultZone: http://localhost:8761/eureka/ #注册中心地址
logging:
  level: INFO
  
example:
    service:
      enabled: true
      config: abc-des-dde,SSS-DRS-RE,SDR-SDFR-XXX